/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
/**
 *
 * @author Victor
 */
public class VistaAgenda extends javax.swing.JFrame {

    /**
     * Creates new form VistaAgenda
     */
    
    AgendaBD agenda;
    Contacto contacto;
    
    public VistaAgenda() {
        initComponents();
        setLocationRelativeTo(null);
        agenda = new AgendaBD();
        rellenarListaDesplegable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dAviso = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bAceptarDialog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cAgenda = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tLocalidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tTelefono = new javax.swing.JTextField();
        tEmail = new javax.swing.JTextField();
        tEdad = new javax.swing.JTextField();
        bNuevo = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();

        dAviso.setTitle("Agenda sin contactos");
        dAviso.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Agenda Vacia");
        dAviso.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("No se pueden eliminar contactos, por que no existen.");
        dAviso.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        bAceptarDialog.setText("Aceptar");
        bAceptarDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarDialog(evt);
            }
        });
        dAviso.getContentPane().add(bAceptarDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");
        setMinimumSize(new java.awt.Dimension(560, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Contactos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        cAgenda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cambioContacto(evt);
            }
        });
        getContentPane().add(cAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 190, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 480, 10));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });
        getContentPane().add(tNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 190, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Direccion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        tDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(tDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 190, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Localidad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        tLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLocalidadActionPerformed(evt);
            }
        });
        getContentPane().add(tLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 190, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Edad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        tTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(tTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 190, -1));

        tEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEmailActionPerformed(evt);
            }
        });
        getContentPane().add(tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 190, -1));
        getContentPane().add(tEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 190, -1));

        bNuevo.setText("Nuevo");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoContacto(evt);
            }
        });
        getContentPane().add(bNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarContacto(evt);
            }
        });
        getContentPane().add(bModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borradoContacto(evt);
            }
        });
        getContentPane().add(bBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirPrograma(evt);
            }
        });
        getContentPane().add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambioContacto(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cambioContacto
        String nom = (String) cAgenda.getSelectedItem();
        Contacto contacto = agenda.obtenerContacto(nom);
        
        //COMPROBACION QUE EL CONTACTO NO ESTE VACIO
        if (contacto != null) {
            tNombre.setText(contacto.getNombre());
            tDireccion.setText(contacto.getDireccion());
            tLocalidad.setText(contacto.getLocalidad());
            tTelefono.setText(contacto.getTelefono());
            tEmail.setText(contacto.getMail());
            tEdad.setText(""+contacto.getEdad());            
        }
    }//GEN-LAST:event_cambioContacto

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        tDireccion.requestFocus();
    }//GEN-LAST:event_tNombreActionPerformed

    private void tDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDireccionActionPerformed
        tLocalidad.requestFocus();
    }//GEN-LAST:event_tDireccionActionPerformed

    private void tLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLocalidadActionPerformed
        tTelefono.requestFocus();
    }//GEN-LAST:event_tLocalidadActionPerformed

    private void tTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTelefonoActionPerformed
        tEmail.requestFocus();
    }//GEN-LAST:event_tTelefonoActionPerformed

    private void tEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEmailActionPerformed
        tEdad.requestFocus();
    }//GEN-LAST:event_tEmailActionPerformed

    private void salirPrograma(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirPrograma
        System.exit(0);
    }//GEN-LAST:event_salirPrograma

    private void nuevoContacto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoContacto
        String nombre = tNombre.getText();
        String direccion = tDireccion.getText();
        String localidad = tLocalidad.getText();
        String telefono = tTelefono.getText();
        String correo = tEmail.getText();
        int edad = Integer.parseInt(tEdad.getText());
        
        contacto = new Contacto(nombre, direccion, localidad, telefono, correo, edad);
        agenda.creacionContacto(contacto);
        
        rellenarListaDesplegable();
    }//GEN-LAST:event_nuevoContacto

    private void modificarContacto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarContacto
        String nombre = tNombre.getText();
        String direccion = tDireccion.getText();
        String localidad = tLocalidad.getText();
        String telefono = tTelefono.getText();
        String correo = tEmail.getText();
        int edad = Integer.parseInt(tEdad.getText());
        
        contacto = new Contacto(nombre, direccion, localidad, telefono, correo, edad);
        agenda.modificarContacto(contacto, (String) cAgenda.getSelectedItem());
        
        rellenarListaDesplegable();
    }//GEN-LAST:event_modificarContacto

    private void borradoContacto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borradoContacto
              
        if (cAgenda.getItemCount() >= 0) {
            String nombre = tNombre.getText();
            String direccion = tDireccion.getText();
            String localidad = tLocalidad.getText();
            String telefono = tTelefono.getText();
            String correo = tEmail.getText();
            int edad = Integer.parseInt(tEdad.getText());
        
            contacto = new Contacto(nombre, direccion, localidad, telefono, correo, edad);
            agenda.borrarContacto(contacto);
        
            rellenarListaDesplegable();
        }else{
            dAviso.setVisible(true);
        }
    }//GEN-LAST:event_borradoContacto

    private void cerrarDialog(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarDialog
        dAviso.setVisible(false);
    }//GEN-LAST:event_cerrarDialog
    
    public void rellenarListaDesplegable(){
        ResultSet res = agenda.obtenerRegistros("contactos");
        try {
            if (res != null) {
                cAgenda.removeAllItems();
                while (res.next()) {                    
                    cAgenda.addItem( res.getString("nombre") );
                }
            }
        } catch (SQLException e) {
            System.out.println("Error rellenar la lista");
        }
    }   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptarDialog;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> cAgenda;
    private javax.swing.JDialog dAviso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tDireccion;
    private javax.swing.JTextField tEdad;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tLocalidad;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables
}
