
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victor
 */
public class Ejercicio3 extends javax.swing.JFrame implements Runnable {
    int num1, num2;
    Cuenta hilo1;
    Descuenta hilo2;
    /**
     * Creates new form Ejercicio3
     */
    public Ejercicio3() {
        initComponents();
    }

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    class Cuenta extends Thread{
        public Cuenta(String nom){super(nom);}
        public void run(){
            try{
                num1=Integer.parseInt(tfContar.getText());
            }catch(NumberFormatException e){
                num1=0;
            }
            while(num1 <= 100 && Thread.currentThread() == hilo1) {
                tfContar.setText("" + num1);
                try {                  
                    Thread.sleep(1000);                   
                } catch (InterruptedException ex) {}
                num1++;
            }
        }
    }
    
    class Descuenta extends Thread{
        public Descuenta(String nom){super(nom);}
        public void run(){
            try{
                num2=Integer.parseInt(tfDescontar.getText());
            }catch(NumberFormatException e){
                num2=100;
            }
            while(num2 >= 0 && Thread.currentThread() == hilo2) {
                tfDescontar.setText("" + num2);
                try {                   
                    Thread.sleep(1000);                   
                } catch (InterruptedException ex) {}
                num2--;
            }
        }
    }
    
    
    public void nuevoHilo1() {
        if(hilo1==null) {
            hilo1 = new Cuenta("Hilo Cuenta");
            hilo1.start();      
        }
    }
    
    public void nuevoHilo2() {
        if(hilo2==null) {
            hilo2 = new Descuenta("Hilo Descuenta");
            hilo2.start();      
        }
    }
    
    public void finalizarHilo1() {
        hilo1=null;  
    }
    
    public void finalizarHilo2() {
        hilo2=null;  
    }
    
    
    /**
     *
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfContar = new javax.swing.JTextField();
        tfDescontar = new javax.swing.JTextField();
        bPararC = new javax.swing.JButton();
        bReanudarC = new javax.swing.JButton();
        bComenzarC = new javax.swing.JButton();
        bPararD = new javax.swing.JButton();
        bReanudarD = new javax.swing.JButton();
        bComenzarD = new javax.swing.JButton();
        bFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bPararC.setText("Parar");
        bPararC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPararCActionPerformed(evt);
            }
        });

        bReanudarC.setText("Reanudar");
        bReanudarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReanudarCActionPerformed(evt);
            }
        });

        bComenzarC.setText("Comenzar");
        bComenzarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComenzarCActionPerformed(evt);
            }
        });

        bPararD.setText("Parar");
        bPararD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPararDActionPerformed(evt);
            }
        });

        bReanudarD.setText("Reanudar");
        bReanudarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReanudarDActionPerformed(evt);
            }
        });

        bComenzarD.setText("Comenzar");
        bComenzarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComenzarDActionPerformed(evt);
            }
        });

        bFinalizar.setText("Finalizar");
        bFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bPararC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfContar)
                            .addComponent(bReanudarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bComenzarC, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDescontar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bComenzarD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(bPararD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bReanudarD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfContar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDescontar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPararD)
                    .addComponent(bPararC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bReanudarC)
                    .addComponent(bReanudarD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bComenzarC)
                    .addComponent(bComenzarD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bFinalizar)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bComenzarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComenzarCActionPerformed
        nuevoHilo1();
    }//GEN-LAST:event_bComenzarCActionPerformed

    private void bComenzarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComenzarDActionPerformed
        nuevoHilo2();
    }//GEN-LAST:event_bComenzarDActionPerformed

    private void bPararCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPararCActionPerformed
        if(hilo1!=null){
            hilo1.suspend();
        }
    }//GEN-LAST:event_bPararCActionPerformed

    private void bPararDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPararDActionPerformed
        if(hilo2!=null){
            hilo2.suspend();
        }
    }//GEN-LAST:event_bPararDActionPerformed

    private void bReanudarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReanudarCActionPerformed
        if(hilo1!=null){
            hilo1.resume();
        }
    }//GEN-LAST:event_bReanudarCActionPerformed

    private void bReanudarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReanudarDActionPerformed
        if(hilo2!=null){
            hilo2.resume();
        }
    }//GEN-LAST:event_bReanudarDActionPerformed

    private void bFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinalizarActionPerformed
        finalizarHilo1();
        finalizarHilo2();
        tfContar.setText(null);
        tfDescontar.setText(null);
    }//GEN-LAST:event_bFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bComenzarC;
    private javax.swing.JButton bComenzarD;
    private javax.swing.JButton bFinalizar;
    private javax.swing.JButton bPararC;
    private javax.swing.JButton bPararD;
    private javax.swing.JButton bReanudarC;
    private javax.swing.JButton bReanudarD;
    private javax.swing.JTextField tfContar;
    private javax.swing.JTextField tfDescontar;
    // End of variables declaration//GEN-END:variables

    
}
