
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victor
 */
public class HiloCuenta extends javax.swing.JFrame{

    /**
     * Creates new form CalculadoraMedia
     */
    public HiloCuenta() {
        initComponents();
    }
    double suma = 0;
    int cont = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dVacio = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lNota = new javax.swing.JLabel();
        tNota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tContador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tNotaMedia = new javax.swing.JTextField();
        bAdd = new javax.swing.JButton();
        bCalcular = new javax.swing.JButton();
        bNuevo = new javax.swing.JButton();

        dVacio.setTitle("Error");
        dVacio.setLocationByPlatform(true);
        dVacio.setMinimumSize(new java.awt.Dimension(400, 300));
        dVacio.setModal(true);
        dVacio.setResizable(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Valor incorrecto o campo vacio");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout dVacioLayout = new javax.swing.GroupLayout(dVacio.getContentPane());
        dVacio.getContentPane().setLayout(dVacioLayout);
        dVacioLayout.setHorizontalGroup(
            dVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dVacioLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(dVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dVacioLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dVacioLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(83, 83, 83))))
        );
        dVacioLayout.setVerticalGroup(
            dVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dVacioLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Medias");
        setMinimumSize(new java.awt.Dimension(600, 300));
        setResizable(false);

        lNota.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lNota.setText("Nota");

        tNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNotaCampo(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Contador");

        tContador.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Nota Media");

        tNotaMedia.setEditable(false);

        bAdd.setText("Añadir");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNota(evt);
            }
        });

        bCalcular.setText("Calcular");
        bCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularMedia(evt);
            }
        });

        bNuevo.setText("Nuevo");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nuevo(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(bAdd)
                        .addGap(95, 95, 95)
                        .addComponent(bCalcular)
                        .addGap(82, 82, 82)
                        .addComponent(bNuevo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tNotaMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(lNota)
                                .addGap(18, 18, 18)
                                .addComponent(tNota, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addComponent(tContador, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNota)
                    .addComponent(jLabel1)
                    .addComponent(tContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tNotaMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAdd)
                    .addComponent(bCalcular)
                    .addComponent(bNuevo))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddNota(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNota
        double nota = 0;
        try {
            nota = ControlRango(Double.parseDouble( tNota.getText() ));
            
            suma += nota;
            cont++;

            tContador.setText("" + cont);
            tNota.setText(null);
            tNota.requestFocus();
        } catch (NumberFormatException e) {
            dVacio.setVisible(true);
            tNota.setText(null);
            tNota.requestFocus();
        } catch (RangoNumeroException ex) {
            dVacio.setVisible(true);
            tNota.setText(null);
            tNota.requestFocus();
        }              
        
    }//GEN-LAST:event_AddNota

    private void AddNotaCampo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNotaCampo
        double nota = 0;
        try {
            nota = ControlRango(Double.parseDouble( tNota.getText() ));
            
            suma += nota;
            cont++;

            tContador.setText("" + Math.round(cont) );
            tNota.setText(null);
            tNota.requestFocus();
        } catch (NumberFormatException e) {
            dVacio.setVisible(true);
            tNota.setText(null);
            tNota.requestFocus();
        } catch (RangoNumeroException ex) {
            dVacio.setVisible(true);
            tNota.setText(null);
            tNota.requestFocus();
        }
    }//GEN-LAST:event_AddNotaCampo

    private void CalcularMedia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularMedia
        try {            
            tNotaMedia.setText(""+Mate.divide(suma, cont));
        } catch (DivisionPorCeroException ex) {
            System.out.println("Division de resultado 0");
        }
    }//GEN-LAST:event_CalcularMedia

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dVacio.setVisible(false);
        tNota.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Nuevo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nuevo
        tNota.setText(null);
        tContador.setText(null);
        tNotaMedia.setText(null);
        tNota.requestFocus();
        cont = 0;
        suma = 0;
    }//GEN-LAST:event_Nuevo

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    dVacio.setVisible(false);
        }
    }//GEN-LAST:event_jButton1KeyPressed
    
    public static double ControlRango(double num) throws RangoNumeroException{
        if (num < 0 || num > 10) {
            RangoNumeroException error = new RangoNumeroException();
            throw error;
        }
        return num;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HiloCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HiloCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HiloCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HiloCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HiloCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bCalcular;
    private javax.swing.JButton bNuevo;
    private javax.swing.JDialog dVacio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lNota;
    private javax.swing.JTextField tContador;
    private javax.swing.JTextField tNota;
    private javax.swing.JTextField tNotaMedia;
    // End of variables declaration//GEN-END:variables
}
