
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victor
 */
public class VistaMulta extends javax.swing.JFrame {

    /**
     * Creates new form VistaMulta
     */
    Controlador control;
    Coche automovil;
    
    DefaultTableModel modelo = new DefaultTableModel();
    
    public VistaMulta() {
        control = new Controlador();
        initComponents();
        rellenarLista();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cConductores = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tCoche = new javax.swing.JTextField();
        tMatricula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de multas");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Conductor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 43, -1, -1));

        cConductores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                datosCoche(evt);
            }
        });
        getContentPane().add(cConductores, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 230, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 82, 550, 10));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Datos Coche");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel3.setText("Coche");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel4.setText("Matricula");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        tCoche.setEditable(false);
        getContentPane().add(tCoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 220, -1));

        tMatricula.setEditable(false);
        getContentPane().add(tMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 220, -1));

        jTable1.setModel(modelo);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 570, 190));

        jButton1.setText("Consultar");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarConsulta(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 100, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirApp(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datosCoche(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_datosCoche
        String nombre = (String) cConductores.getSelectedItem();
        Coche auto = control.obtenerCoche(nombre);
        
        if (auto != null) {
            tCoche.setText(auto.getCoche());
            tMatricula.setText(auto.getMatricula());
        }
    }//GEN-LAST:event_datosCoche

    private void mostrarConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarConsulta
        modelo.setRowCount(0);
        modelo.setColumnCount(0);
        modelo.addColumn("Infraccion");
        modelo.addColumn("Fecha");
        modelo.addColumn("Penalizacion");
        
        ResultSet resultado = control.obtenerInfraccion((String) cConductores.getSelectedItem());
                
        try {            
            while (resultado.next()) {
                modelo.addRow(new Object[]{resultado.getString("infraccion"),resultado.getString("fecha"),resultado.getInt("penalizacion")});                
            }
        } catch (SQLException e) {
            System.out.println("FALLO mostrarConsulta()");
        }
    }//GEN-LAST:event_mostrarConsulta

    private void salirApp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirApp
        System.exit(0);
    }//GEN-LAST:event_salirApp

    /**
     * @param args the command line arguments
     */
    
    public void rellenarLista(){
        ResultSet resultado = control.obtenerRegistros("Coches");
        try {
            if (resultado != null) {
                cConductores.removeAllItems();
                while (resultado.next()) {                    
                    cConductores.addItem( resultado.getString("nombre") );
                }
            }
        } catch (SQLException e) {
            System.out.println("FALLO rellenarLista()");
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cConductores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tCoche;
    private javax.swing.JTextField tMatricula;
    // End of variables declaration//GEN-END:variables
}
