
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victo
 */
public class Ahorcado extends javax.swing.JFrame {

    /**
     * Creates new form Ahorcado
     */
    
    ArrayList palabras = new ArrayList();
    public Ahorcado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dPalabras = new javax.swing.JDialog();
        bAñadir = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tNuevaPalabra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tPalabra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tLetra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tIntentos = new javax.swing.JTextField();
        bPalabras = new javax.swing.JButton();
        bJugar = new javax.swing.JButton();
        bFinalizar = new javax.swing.JButton();

        dPalabras.setTitle("Guardar Palabras");
        dPalabras.setMinimumSize(new java.awt.Dimension(562, 222));

        bAñadir.setText("Añadir");
        bAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirPalabras(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarDialog(evt);
            }
        });

        jLabel4.setText("Palabra:");

        javax.swing.GroupLayout dPalabrasLayout = new javax.swing.GroupLayout(dPalabras.getContentPane());
        dPalabras.getContentPane().setLayout(dPalabrasLayout);
        dPalabrasLayout.setHorizontalGroup(
            dPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPalabrasLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addGroup(dPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dPalabrasLayout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(bAñadir)
                        .addGap(114, 114, 114)
                        .addComponent(bSalir)
                        .addGap(140, 140, 140))
                    .addGroup(dPalabrasLayout.createSequentialGroup()
                        .addComponent(tNuevaPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        dPalabrasLayout.setVerticalGroup(
            dPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dPalabrasLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(dPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tNuevaPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(dPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalir)
                    .addComponent(bAñadir))
                .addGap(59, 59, 59))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego del ahorcado");
        setMinimumSize(new java.awt.Dimension(862, 287));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Palabra");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        tPalabra.setEditable(false);
        getContentPane().add(tPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 340, -1));

        jLabel2.setText("Letra");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        tLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                introducirLetra(evt);
            }
        });
        getContentPane().add(tLetra, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 90, -1));

        jLabel3.setText("Intentos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        tIntentos.setEditable(false);
        getContentPane().add(tIntentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 90, -1));

        bPalabras.setText("Introducir palabras");
        bPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPalabras(evt);
            }
        });
        getContentPane().add(bPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 180, -1));

        bJugar.setText("Jugar");
        bJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugar(evt);
            }
        });
        getContentPane().add(bJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        bFinalizar.setText("Finalizar");
        bFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarApp(evt);
            }
        });
        getContentPane().add(bFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirPalabras(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPalabras
        dPalabras.setVisible(true);
    }//GEN-LAST:event_abrirPalabras
    
    // ESTA FUNCION AÑADE CADA PALABRA QUE ESCRIBIMOS A UN ARRALIST
    private void añadirPalabras(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirPalabras
        tNuevaPalabra.requestFocus();
        palabras.add(tNuevaPalabra.getText());
        for (int i = 0; i < palabras.size(); i++) {
            System.out.println(palabras.get(i));            
        }
        tNuevaPalabra.setText(null);
    }//GEN-LAST:event_añadirPalabras

    private void cerrarDialog(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarDialog
        dPalabras.setVisible(false);
        tLetra.requestFocus();
    }//GEN-LAST:event_cerrarDialog

    private void cerrarApp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarApp
        System.exit(0);
    }//GEN-LAST:event_cerrarApp

    private void jugar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugar
        if (palabras.isEmpty()) {
            System.out.println("ARRAY DE PALABRAS VACIO");
        }else{
            tIntentos.setText("" + 5);
            tLetra.setText(null);
            tLetra.requestFocus();             
                
            int numAux = (int) ( palabras.size() * Math.random() );
            String palabraAux = (String) palabras.get(numAux);
            System.out.println(palabraAux);
            String palabraEnc="";
            for (int i = 0; i < palabraAux.length(); i++) {
                palabraEnc = palabraEnc+"_";
            }
            tPalabra.setText(palabraEnc);
            
        }
        
    }//GEN-LAST:event_jugar

    private void introducirLetra(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_introducirLetra
        
    }//GEN-LAST:event_introducirLetra

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAñadir;
    private javax.swing.JButton bFinalizar;
    private javax.swing.JButton bJugar;
    private javax.swing.JButton bPalabras;
    private javax.swing.JButton bSalir;
    private javax.swing.JDialog dPalabras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tIntentos;
    private javax.swing.JTextField tLetra;
    private javax.swing.JTextField tNuevaPalabra;
    private javax.swing.JTextField tPalabra;
    // End of variables declaration//GEN-END:variables
}
