/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Victor
 */
import java.sql.*;
import javax.swing.table.DefaultTableModel;
public class VistaEstadisticas extends javax.swing.JFrame {

    /**
     * Creates new form VistaEstadisticas
     */
    Controlador control;
    DefaultTableModel modelo;
    public VistaEstadisticas() {
        control = new Controlador();
        modelo = new DefaultTableModel();
        setLocationRelativeTo(null);
        initComponents();
        obtenerCurso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cCurso = new java.awt.Choice();
        cEvaluacion = new java.awt.Choice();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tEstadisticas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estadisticas Alumnos");
        setMinimumSize(new java.awt.Dimension(800, 350));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Curso/Evaluacion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 690, -1));

        jLabel2.setText("Curso");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel3.setText("Evaluacion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));
        getContentPane().add(cCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 120, -1));

        cEvaluacion.addItem("Evaluacion 1");
        cEvaluacion.addItem("Evaluacion 2");
        cEvaluacion.addItem("Evaluacion 3");
        cEvaluacion.addItem("Evaluacion Final");
        getContentPane().add(cEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 120, -1));

        jLabel4.setText("Notas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 680, 10));

        tEstadisticas.setModel(modelo);
        jScrollPane1.setViewportView(tEstadisticas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 580, 200));

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarEstadisticas(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, -1, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarEstadisticas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarEstadisticas
        modelo.setColumnCount(0);
        modelo.setRowCount(0);
        
        ResultSet asignaturas = control.obtenerAsignaturas(cCurso.getSelectedItem());  
        int numAlumnos = control.numAlumnos(cCurso.getSelectedItem());
        int numAsignaturas = control.numAsignaturas(cCurso.getSelectedItem());
        try {
            // FORMATO TABLA
            if (asignaturas != null) {
                modelo.addColumn("    ");
                modelo.addRow(new Object[]{"Insuficiente"});
                modelo.addRow(new Object[]{"Suficiente"});
                modelo.addRow(new Object[]{"Bien"});
                modelo.addRow(new Object[]{"Notable"});
                modelo.addRow(new Object[]{"Sobresaliente"});
                while (asignaturas.next()) {                
                    modelo.addColumn(asignaturas.getString("asignatura"));
                }
            }
            // CONTENIDO
            for (int i = 0; i < numAsignaturas; i++) {
                int insuficiente = 0,suficiente = 0,bien = 0,notable = 0,sobresaliente = 0;
                ResultSet notas = control.notasAsignatura(cEvaluacion.getSelectedItem(), modelo.getColumnName(i+1));
                if (notas != null) {
                    while (notas.next()) {                    
                        if (notas.getInt("nota") < 5) {
                            insuficiente++;
                        } else if(notas.getInt("nota") == 5){
                            suficiente++;
                        } else if(notas.getInt("nota") == 6){
                            bien++;
                        } else if(notas.getInt("nota") == 7 || notas.getInt("nota") == 8){
                            notable++;
                        } else if(notas.getInt("nota") == 9 || notas.getInt("nota") == 10){
                            sobresaliente++;
                        }
                    }
                }
                modelo.setValueAt(""+(float)(insuficiente*100/numAlumnos)+" %", 0, i+1);
                modelo.setValueAt(""+(float)(suficiente*100/numAlumnos)+" %", 1, i+1);
                modelo.setValueAt(""+(float)(bien*100/numAlumnos)+" %", 2, i+1);
                modelo.setValueAt(""+(float)(notable*100/numAlumnos)+" %", 3, i+1);
                modelo.setValueAt(""+(float)(sobresaliente*100/numAlumnos)+" %", 4, i+1);
            }
            
            
        } catch (SQLException e) {
            System.out.println("FALLO CREACION TABLA");
        }
    }//GEN-LAST:event_consultarEstadisticas

    private void salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir
        System.exit(0);
    }//GEN-LAST:event_salir
    
    private void obtenerCurso(){
        ResultSet resultado = control.obtenerCurso();
        try {
            if (resultado != null) {
                while (resultado.next()) {                    
                    cCurso.addItem(resultado.getString("curso"));
                }
            }
        } catch (SQLException e) {
            System.out.println("Fallo obtenerCurso()");
        }
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEstadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice cCurso;
    private java.awt.Choice cEvaluacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tEstadisticas;
    // End of variables declaration//GEN-END:variables
}
