
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victo
 */
public class VistaEstadisticas extends javax.swing.JFrame {

    /**
     * Creates new form VistaEstadisticas
     */
    Controlador control;
    DefaultTableModel modelo;
    DefaultTableModel modelo2;
    
    public VistaEstadisticas() {
        control  = new Controlador();
        modelo = new DefaultTableModel();
        modelo2 = new DefaultTableModel();
        initComponents();
        setLocationRelativeTo(null);
        pack();
        rellenarJornada();
        
        // MODELO 
        modelo.addColumn("Equipo Local");
        modelo.addColumn("Canastas de 1");
        modelo.addColumn("Canastas de 2");
        modelo.addColumn("Canastas de 3");
        
        // MODELO2
        modelo2.addColumn("Equipo Visitante");
        modelo2.addColumn("Canastas de 1");
        modelo2.addColumn("Canastas de 2");
        modelo2.addColumn("Canastas de 3");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        cJornada = new java.awt.Choice();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        tFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estadisticas del partido");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1050, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Jornada");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Fecha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 900, 10));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirSistema(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 100, -1));

        cJornada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cambioJornada(evt);
            }
        });
        getContentPane().add(cJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 140, -1));

        jButton2.setText("Aceptar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 100, -1));

        jTable1.setModel(modelo);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 110));

        jTable2.setModel(modelo2);
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, 110));
        getContentPane().add(tFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirSistema(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirSistema
        System.exit(0);
    }//GEN-LAST:event_salirSistema

    private void cambioJornada(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cambioJornada
        rellenarFecha();
    }//GEN-LAST:event_cambioJornada
    
    private void rellenarJornada(){
        ResultSet resultado = control.obtenerJornada();
        try {
            if (resultado != null) {
                cJornada.removeAll();
                while (resultado.next()) {                    
                    cJornada.addItem( resultado.getString("jornada") );
                    tFecha.setText( resultado.getString("fecha") );
                }
            }
        } catch (SQLException e) {
            System.out.println("Fallo rellenarJornada");
        }
    }
    
    private void rellenarFecha(){
        ResultSet resultado = control.obtenerFecha(cJornada.getSelectedItem());
        try {
            if (resultado != null) {
                tFecha.setText( resultado.getString("fecha"));
           }
        } catch (SQLException e) {
            System.out.println("Fallo rellenarFecha");
        }
    }
    
    private void rellenarTablas(){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEstadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice cJornada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField tFecha;
    // End of variables declaration//GEN-END:variables
}
