/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victo
 */
public class Ejercicio5 extends javax.swing.JFrame implements Runnable{
    
    int horas,minutos,segundos;
    Thread contador;
    
    /**
     * Creates new form Ejercicio5
     */
    public Ejercicio5() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dHora = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tHora = new javax.swing.JTextField();
        tMinuto = new javax.swing.JTextField();
        tSegundo = new javax.swing.JTextField();
        bAceptarCambios = new javax.swing.JButton();
        tReloj = new javax.swing.JTextField();
        bResetear = new javax.swing.JButton();
        bParar = new javax.swing.JButton();
        bReanudar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        dHora.setTitle("Poner en Hora");

        jLabel1.setText("Horas");

        jLabel2.setText("Minutos");

        jLabel3.setText("Segundos");

        tHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHoraActionPerformed(evt);
            }
        });

        bAceptarCambios.setText("Aceptar");
        bAceptarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCambios(evt);
            }
        });

        javax.swing.GroupLayout dHoraLayout = new javax.swing.GroupLayout(dHora.getContentPane());
        dHora.getContentPane().setLayout(dHoraLayout);
        dHoraLayout.setHorizontalGroup(
            dHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dHoraLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(dHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(dHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tMinuto, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                        .addComponent(tSegundo))
                    .addComponent(tHora, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(bAceptarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        dHoraLayout.setVerticalGroup(
            dHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dHoraLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(dHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(dHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dHoraLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(dHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dHoraLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAceptarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGroup(dHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 300));
        setResizable(false);

        tReloj.setEditable(false);
        tReloj.setText("00:00:00");
        tReloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRelojActionPerformed(evt);
            }
        });

        bResetear.setText("Resetear");
        bResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resetear(evt);
            }
        });

        bParar.setText("Parar");
        bParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parar(evt);
            }
        });

        bReanudar.setText("Reanudar");
        bReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reanudar(evt);
            }
        });

        jButton1.setText("Poner en Hora");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PonerEnHora(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(bResetear, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bParar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(tReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(bReanudar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(tReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bResetear)
                    .addComponent(bParar)
                    .addComponent(bReanudar))
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tRelojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRelojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRelojActionPerformed

    private void tHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHoraActionPerformed

    private void PonerEnHora(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PonerEnHora
        dHora.setVisible(true);
        dHora.pack();
        dHora.setLocationRelativeTo(null);
        tHora.setText(null);
        tMinuto.setText(null);
        tSegundo.setText(null);
        contador.suspend();
        contador = null;
    }//GEN-LAST:event_PonerEnHora

    private void BotonCambios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCambios

        try{ 
            horas = Integer.parseInt( tHora.getText() );
        }catch(NumberFormatException e){
            horas = 0;
        }
        
        if (horas >= 24) {
            horas = 0;
        }
        
        try {
            minutos = Integer.parseInt( tMinuto.getText() );
        } catch (NumberFormatException e) {
            minutos = 0;
        }
        
        if (minutos >= 60) {
            minutos = 0;
        }
        
        try {
            segundos = Integer.parseInt( tSegundo.getText() );
        } catch (NumberFormatException e) {
            segundos = 0;
        }
        
        if (segundos >= 60) {
            segundos = 0;
        }
        
        dHora.setVisible(false);
        
        if (contador == null) {
            contador = new Thread(this);
            contador.start();
        }
        
    }//GEN-LAST:event_BotonCambios

    private void Resetear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resetear
        contador.suspend();
        contador = null;
        tReloj.setText("00:00:00");
    }//GEN-LAST:event_Resetear

    private void Parar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parar
        contador.suspend();
    }//GEN-LAST:event_Parar

    private void Reanudar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reanudar
        contador.resume();
    }//GEN-LAST:event_Reanudar
    
    public void contar() throws InterruptedException{
        for (int i = 0; i < 1000000000; i++) {
            segundos++;
            Thread.sleep(1000);
            
            if (segundos >= 60) {
                segundos = 0;
                minutos++;
                if (minutos >= 60) {
                    minutos = 0;
                    horas++;
                    if (horas >= 24) {
                        horas = 0;
                        horas++;
                    }
                }
            }
            tReloj.setText("" + horas + ":" + minutos + ":" + segundos);
        }
    }
    
    public void run(){
        try {
            contar();
        } catch (InterruptedException e) {}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptarCambios;
    private javax.swing.JButton bParar;
    private javax.swing.JButton bReanudar;
    private javax.swing.JButton bResetear;
    private javax.swing.JDialog dHora;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tHora;
    private javax.swing.JTextField tMinuto;
    private javax.swing.JTextField tReloj;
    private javax.swing.JTextField tSegundo;
    // End of variables declaration//GEN-END:variables
}
