/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victor
 */
public class Practica6 extends java.awt.Frame {

    /**
     * Creates new form Practica6
     */
    public Practica6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dNuevo = new javax.swing.JDialog();
        lAdd = new javax.swing.JLabel();
        tAdd = new javax.swing.JTextField();
        bAdd = new javax.swing.JButton();
        tTitulo = new javax.swing.JLabel();
        lIzquierda = new java.awt.List();
        lDerecha = new java.awt.List();
        bNuevo = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bVaciar = new javax.swing.JButton();
        bGenerar = new javax.swing.JButton();

        dNuevo.setTitle("Recogida de Partido");
        dNuevo.setMinimumSize(new java.awt.Dimension(600, 150));
        dNuevo.setResizable(false);
        dNuevo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lAdd.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lAdd.setText("Partido :");
        dNuevo.getContentPane().add(lAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        tAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAddActionPerformed(evt);
            }
        });
        dNuevo.getContentPane().add(tAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 220, 30));

        bAdd.setText("Añadir");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlBotonAdd(evt);
            }
        });
        dNuevo.getContentPane().add(bAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 100, 60));

        setBackground(new java.awt.Color(60, 63, 65));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(600, 450));
        setResizable(false);
        setTitle("Generador de Quinielas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tTitulo.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        tTitulo.setForeground(new java.awt.Color(187, 0, 0));
        tTitulo.setText("Generador de quiniela");
        add(tTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        add(lIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 180, 300));
        add(lDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 180, 300));

        bNuevo.setText("Nuevo");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlBotonNuevo(evt);
            }
        });
        add(bNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 100, -1));

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlBotonBorrar(evt);
            }
        });
        add(bBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 100, -1));

        bVaciar.setText("Vaciar");
        bVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlBotonVaciar(evt);
            }
        });
        add(bVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 100, -1));

        bGenerar.setText("Generar");
        bGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlBotonGenerar(evt);
            }
        });
        add(bGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void ControlBotonVaciar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlBotonVaciar
        lIzquierda.removeAll();
        lDerecha.removeAll();
    }//GEN-LAST:event_ControlBotonVaciar

    private void ControlBotonNuevo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlBotonNuevo
        dNuevo.setVisible(true);
    }//GEN-LAST:event_ControlBotonNuevo

    private void ControlBotonAdd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlBotonAdd
       lIzquierda.add(tAdd.getText());
       tAdd.setText(null);
       tAdd.requestFocus();
    }//GEN-LAST:event_ControlBotonAdd

    private void ControlBotonBorrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlBotonBorrar
        try{
            lIzquierda.remove(lIzquierda.getSelectedIndex());
        }catch(ArrayIndexOutOfBoundsException e){}
    }//GEN-LAST:event_ControlBotonBorrar

    private void ControlBotonGenerar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlBotonGenerar
        for (int i = 0; i < lIzquierda.getItemCount() ; i++) {
            int num = (int) (Math.random() * 100+1);
            if (num <= 60) {
                    lDerecha.add(lIzquierda.getItem(i)+" 1 ");
            }else if(num <= 90){
                     lDerecha.add(lIzquierda.getItem(i)+" X ");
            }else{
                    lDerecha.add(lIzquierda.getItem(i)+" 2 ");
            }
        }
    }//GEN-LAST:event_ControlBotonGenerar

    private void tAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAddActionPerformed
        lIzquierda.add(tAdd.getText());
        tAdd.setText(null);
        tAdd.requestFocus();
    }//GEN-LAST:event_tAddActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica6().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bGenerar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JButton bVaciar;
    private javax.swing.JDialog dNuevo;
    private javax.swing.JLabel lAdd;
    private java.awt.List lDerecha;
    private java.awt.List lIzquierda;
    private javax.swing.JTextField tAdd;
    private javax.swing.JLabel tTitulo;
    // End of variables declaration//GEN-END:variables
}
