
import java.awt.Dimension;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victor
 */
public class ejercicio3 extends java.awt.Frame {

    /**
     * Creates new form ejercicio3
     */
    public ejercicio3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogNew = new javax.swing.JDialog();
        panel1 = new java.awt.Panel();
        lTemasPreparados = new java.awt.Label();
        tTemasPreparados = new java.awt.TextField();
        bAddThemes = new java.awt.Button();
        lOposicion = new java.awt.Label();
        tNumOposi = new java.awt.TextField();
        lIzquierda = new java.awt.List();
        lDerecha = new java.awt.List();
        lPreparados = new java.awt.Label();
        lObtenidos = new java.awt.Label();
        bAdd = new java.awt.Button();
        bNew = new java.awt.Button();
        bSimulate = new java.awt.Button();
        bGenerate = new java.awt.Button();
        lProb = new java.awt.Label();
        tProb = new java.awt.TextField();
        lProb2 = new java.awt.Label();

        jDialogNew.setTitle("Añadir Temas");
        jDialogNew.setIconImage(null);
        jDialogNew.setMinimumSize(new java.awt.Dimension(350, 350));
        jDialogNew.setResizable(false);
        jDialogNew.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTemasPreparados.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lTemasPreparados.setText("Temas Preparados");
        panel1.add(lTemasPreparados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 320, 70));
        panel1.add(tTemasPreparados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 180, -1));

        bAddThemes.setLabel("Añadir");
        bAddThemes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlAddThemes(evt);
            }
        });
        panel1.add(bAddThemes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 90, 40));

        jDialogNew.getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 300));

        setLocationRelativeTo(null);
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        setTitle("Practica 5 - Ejercicio 3");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lOposicion.setText("Nº Temas Oposiciones");
        add(lOposicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));
        add(tNumOposi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 90, -1));
        add(lIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 120, 200));
        add(lDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 120, 200));

        lPreparados.setText("Temas Preparados");
        add(lPreparados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        lObtenidos.setText("Temas Obtenidos");
        add(lObtenidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        bAdd.setLabel("Añadir");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlBotonNew(evt);
            }
        });
        add(bAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 90, -1));

        bNew.setLabel("Nuevo");
        bNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlNewButton(evt);
            }
        });
        add(bNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 90, -1));

        bSimulate.setLabel("Simular");
        bSimulate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlSimulateButton(evt);
            }
        });
        add(bSimulate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 90, -1));

        bGenerate.setLabel("Generar");
        bGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlBotonGenerar(evt);
            }
        });
        add(bGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 90, -1));

        lProb.setText("Probabilidad");
        add(lProb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));
        add(tProb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 60, -1));

        lProb2.setText("%");
        add(lProb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void ControlBotonNew(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlBotonNew
        jDialogNew.show(true);
    }//GEN-LAST:event_ControlBotonNew

    private void ControlAddThemes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlAddThemes
        lDerecha.add(tTemasPreparados.getText());
        tTemasPreparados.setText(null);
        tTemasPreparados.requestFocus();
    }//GEN-LAST:event_ControlAddThemes

    private void ControlNewButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlNewButton
        lDerecha.removeAll();
        lIzquierda.removeAll();
        tNumOposi.setText(" ");
        tProb.setText(" ");
    }//GEN-LAST:event_ControlNewButton

    private void ControlSimulateButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlSimulateButton
        int numTemas = Integer.parseInt( tNumOposi.getText() );
        if (lDerecha.getItemCount() >= 3) {
            for (int i = 0; i <= 2; i++) {
                lIzquierda.add(""+ (int) (Math.random() * numTemas + 1));
            }
        }
    }//GEN-LAST:event_ControlSimulateButton

    private void ControlBotonGenerar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlBotonGenerar
        int numTemas = Integer.parseInt( tNumOposi.getText() );
        double numPreparados = lDerecha.getItemCount();
        double division = numPreparados / numTemas;
        double prob = division * 100;
        tProb.setText(""+prob);
    }//GEN-LAST:event_ControlBotonGenerar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio3().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bAdd;
    private java.awt.Button bAddThemes;
    private java.awt.Button bGenerate;
    private java.awt.Button bNew;
    private java.awt.Button bSimulate;
    private javax.swing.JDialog jDialogNew;
    private java.awt.List lDerecha;
    private java.awt.List lIzquierda;
    private java.awt.Label lObtenidos;
    private java.awt.Label lOposicion;
    private java.awt.Label lPreparados;
    private java.awt.Label lProb;
    private java.awt.Label lProb2;
    private java.awt.Label lTemasPreparados;
    private java.awt.Panel panel1;
    private java.awt.TextField tNumOposi;
    private java.awt.TextField tProb;
    private java.awt.TextField tTemasPreparados;
    // End of variables declaration//GEN-END:variables
}
