/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victor
 */
public class ejercicio2 extends java.awt.Frame {

    /**
     * Creates new form ejercicio2
     */
    public ejercicio2() {
        initComponents();
        
        // Inserccion Meses
        cMes.addItem("Enero");
        cMes.addItem("Febrero");
        cMes.addItem("Marzo");
        cMes.addItem("Abril");
        cMes.addItem("Mayo");
        cMes.addItem("Junio");
        cMes.addItem("Julio");
        cMes.addItem("Agosto");
        cMes.addItem("Septiembre");
        cMes.addItem("Octubre");
        cMes.addItem("Noviembre");
        cMes.addItem("Diciembre");  
        
        // Inserccion Dias        
        for (int i = 1; i <= 31; i++) {
            cDia.addItem(i+"");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lDia = new java.awt.Label();
        cDia = new java.awt.Choice();
        lMes = new java.awt.Label();
        cMes = new java.awt.Choice();
        scroll = new java.awt.Scrollbar();
        bReset = new java.awt.Button();

        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setTitle("Practica 3 - Ejercicio 2");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lDia.setText("Dia");
        add(lDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 40, 20));

        cDia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ControlChoice(evt);
            }
        });
        add(cDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        lMes.setText("Mes");
        add(lMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        cMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ControlChoice(evt);
            }
        });
        add(cMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        scroll.setBackground(new java.awt.Color(0, 0, 0));
        scroll.setMaximum(376);
        scroll.setOrientation(java.awt.Scrollbar.HORIZONTAL);
        scroll.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                ControlScroll(evt);
            }
        });
        add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 370, 30));

        bReset.setLabel("Resetear");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlResetear(evt);
            }
        });
        add(bReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void ControlScroll(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_ControlScroll
        int val = evt.getValue();
        System.out.println(val);
        
        if (val <= 30) {
            // Enero
            cDia.select(val);
            cMes.select(0);
        }else if(val <= 58){
            // Febrero
            cDia.select(val - 31);
            cMes.select(1);
        }else if (val <= 89) {
            // Marzo
            cDia.select(val - 59);
            cMes.select(2);
        }else if (val <= 119) {
            // Abril
            cDia.select(val - 90);
            cMes.select(3);
        }else if (val <= 150) {
            //Mayo
            cDia.select(val - 120);
            cMes.select(4);
        }else if (val <= 180) {
            // Junio
            cDia.select(val - 151);
            cMes.select(5);
        }else if (val <= 211) {
            // Julio
            cDia.select(val - 181);
            cMes.select(6);
        }else if (val <= 242) {
            // Agosto
            cDia.select(val - 212);
            cMes.select(7);
        }else if (val <= 272) {
            // Septiembre
            cDia.select(val - 243);
            cMes.select(8);
        }else if (val <= 303) {
            // Octubre
            cDia.select(val - 273);
            cMes.select(9);
        }else if (val <= 333) {
            // Noviembre
            cDia.select(val - 304);
            cMes.select(10);
        }else if (val <= 366) {
            // Diciembre
            cDia.select(val - 334);
            cMes.select(11);
        }
        
        // Controlador dias mes
        switch(cMes.getSelectedItem()){
            case "Enero": ;
            case "Marzo": ;
            case "Mayo": ;
            case "Julio": ;
            case "Agosto": ;
            case "Octubre": ;
            case "Diciembre": 
                if (cDia.getItemCount() == 30) {
                    cDia.add(""+31);
                }
                if (cDia.getItemCount() == 28) {
                    cDia.add(""+29);
                    cDia.add(""+30);
                    cDia.add(""+31);
                }
                ;break;
            case "Abril": ;            
            case "Junio": ;
            case "Septiembre": ;
            case "Noviembre": 
                if (cDia.getItemCount() == 31) {
                    cDia.remove(30);
                }
                if (cDia.getItemCount() == 28) {
                    cDia.add(""+29);
                    cDia.add(""+30);
                }
                ;break;
            case "Febrero":
                if (cDia.getItemCount() == 31) {
                    cDia.remove(30);
                    cDia.remove(29);
                    cDia.remove(28);
                }
                if (cMes.getItemCount() == 30) {
                    cDia.remove(29);
                    cDia.remove(28);
                }
        }
    }//GEN-LAST:event_ControlScroll

    private void ControlResetear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlResetear
        cDia.select(0);
        cMes.select(0);
        scroll.setValue(0);
    }//GEN-LAST:event_ControlResetear

    private void ControlChoice(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ControlChoice
        int dia = Integer.parseInt( cDia.getSelectedItem() );
        String mes = cMes.getSelectedItem();
        System.out.println(mes);
        System.out.println(dia);
        
        // Controlador dias mes
        switch(cMes.getSelectedItem()){
            case "Enero": ;
            case "Marzo": ;
            case "Mayo": ;
            case "Julio": ;
            case "Agosto": ;
            case "Octubre": ;
            case "Diciembre": ;
                if (cDia.getItemCount() == 30) {
                    cDia.add(""+31);
                }
                if (cDia.getItemCount() == 28) {
                    cDia.add(""+29);
                    cDia.add(""+30);
                    cDia.add(""+31);
                }
                ;break;
            case "Abril": ;            
            case "Junio": ;
            case "Septiembre": ;
            case "Noviembre": 
                if (cDia.getItemCount() == 31) {
                    cDia.remove(30);
                }
                if (cDia.getItemCount() == 28) {
                    cDia.add(""+29);
                    cDia.add(""+30);
                }
                ;break;
            case "Febrero":
                if (cDia.getItemCount() == 31) {
                    cDia.remove(30);
                    cDia.remove(29);
                    cDia.remove(28);
                }
                if (cDia.getItemCount() == 30) {
                    cDia.remove(29);
                    cDia.remove(28);
                }
        }
        
        // Controlador scroll por dia/mes
        switch(mes){
            case "Enero": 
                scroll.setValue(dia); 
                break;
            case "Febrero":
                scroll.setValue(dia + 32);
                break;
            case "Marzo":
                scroll.setValue(dia + 60);
                break;  
            case "Abril":
                scroll.setValue(dia + 91);
                break;
            case "Mayo":
                scroll.setValue(dia + 121);
                break;
            case "Junio":
                scroll.setValue(dia + 152);
                break;
            case "Julio":
                scroll.setValue(dia + 182);
                break;
            case "Agosto":
                scroll.setValue(dia + 213);
                break;
            case "Septiembre":
                scroll.setValue(dia + 244);
                break;
            case "Octubre":
                scroll.setValue(dia + 274);
                break;
            case "Noviembre":
                scroll.setValue(dia + 305);
                break;
            case "Diciembre":
                scroll.setValue(dia + 335);
                break;
        }
        
        
    }//GEN-LAST:event_ControlChoice

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio2().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bReset;
    private java.awt.Choice cDia;
    private java.awt.Choice cMes;
    private java.awt.Label lDia;
    private java.awt.Label lMes;
    private java.awt.Scrollbar scroll;
    // End of variables declaration//GEN-END:variables
}
