
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victor
 */
public class Coleccion extends javax.swing.JFrame {

    /**
     * Creates new form Coleccion
     */
    public Coleccion() {
        initComponents();
    }
    // CREACION ARRAY 
    ArrayList<TPersona> agendaContactos = new ArrayList<>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dError = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dBorrar = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        bAceptarBorrar = new javax.swing.JButton();
        bCancelarBorrar = new javax.swing.JButton();
        dBorrarVacio = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        dVacio = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        bBotonCerrarVacio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cContacto = new java.awt.Choice();
        bBorrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        tDireccion = new javax.swing.JTextField();
        tEdad = new javax.swing.JTextField();
        tTelefono = new javax.swing.JTextField();
        bNuevo = new javax.swing.JButton();

        dError.setTitle("ERROR");
        dError.setMinimumSize(new java.awt.Dimension(550, 301));
        dError.setResizable(false);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Los valores deben de ser alfabeticos");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarDialogoClick(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CerrarDialogoBoton(evt);
            }
        });

        javax.swing.GroupLayout dErrorLayout = new javax.swing.GroupLayout(dError.getContentPane());
        dError.getContentPane().setLayout(dErrorLayout);
        dErrorLayout.setHorizontalGroup(
            dErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dErrorLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(56, 56, 56))
            .addGroup(dErrorLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dErrorLayout.setVerticalGroup(
            dErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dErrorLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel8)
                .addGap(49, 49, 49)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        dBorrar.setTitle("Comprobar");
        dBorrar.setLocationByPlatform(true);
        dBorrar.setMinimumSize(new java.awt.Dimension(600, 300));
        dBorrar.setModal(true);
        dBorrar.setResizable(false);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("¿Estas seguro que desea borrar este contacto?");

        bAceptarBorrar.setText("Aceptar");
        bAceptarBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarBorrarActionPerformed(evt);
            }
        });

        bCancelarBorrar.setText("Cancelar");
        bCancelarBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dBorrarLayout = new javax.swing.GroupLayout(dBorrar.getContentPane());
        dBorrar.getContentPane().setLayout(dBorrarLayout);
        dBorrarLayout.setHorizontalGroup(
            dBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dBorrarLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(105, 105, 105))
            .addGroup(dBorrarLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(bAceptarBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(bCancelarBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dBorrarLayout.setVerticalGroup(
            dBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dBorrarLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel9)
                .addGap(55, 55, 55)
                .addGroup(dBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptarBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelarBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        dBorrarVacio.setTitle("ERROR");
        dBorrarVacio.setLocationByPlatform(true);
        dBorrarVacio.setMinimumSize(new java.awt.Dimension(600, 300));
        dBorrarVacio.setModal(true);
        dBorrarVacio.setResizable(false);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Tu agenda esta vacia, no se pueden borrar contactos.");

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dBorrarVacioLayout = new javax.swing.GroupLayout(dBorrarVacio.getContentPane());
        dBorrarVacio.getContentPane().setLayout(dBorrarVacioLayout);
        dBorrarVacioLayout.setHorizontalGroup(
            dBorrarVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dBorrarVacioLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(dBorrarVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dBorrarVacioLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dBorrarVacioLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(343, 343, 343))))
        );
        dBorrarVacioLayout.setVerticalGroup(
            dBorrarVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dBorrarVacioLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel10)
                .addGap(46, 46, 46)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        dVacio.setTitle("Campos vacios");
        dVacio.setMinimumSize(new java.awt.Dimension(450, 300));
        dVacio.setModal(true);
        dVacio.setResizable(false);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Hay campos vacios, completalos");

        bBotonCerrarVacio.setText("Aceptar");
        bBotonCerrarVacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBotonCerrarVacioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dVacioLayout = new javax.swing.GroupLayout(dVacio.getContentPane());
        dVacio.getContentPane().setLayout(dVacioLayout);
        dVacioLayout.setHorizontalGroup(
            dVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dVacioLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(bBotonCerrarVacio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dVacioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(48, 48, 48))
        );
        dVacioLayout.setVerticalGroup(
            dVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dVacioLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel11)
                .addGap(40, 40, 40)
                .addComponent(bBotonCerrarVacio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda de Contactos");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("CONTACTOS");
        jLabel1.setToolTipText("");

        jLabel2.setText("Selecciona");

        cContacto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MostrarColeccion(evt);
            }
        });

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarContacto(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Datos de Contacto");

        jLabel4.setText("Nombre");

        jLabel5.setText("Direccion");

        jLabel6.setText("Edad");

        jLabel7.setText("Telefono");

        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });

        tDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDireccionActionPerformed(evt);
            }
        });

        tEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEdadActionPerformed(evt);
            }
        });
        tEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ControlEdad(evt);
            }
        });

        tTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTelefonoActionPerformed(evt);
            }
        });
        tTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ControlTelefono(evt);
            }
        });

        bNuevo.setText("Nuevo");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPersona(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(46, 46, 46)
                                .addComponent(cContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(66, 66, 66))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(57, 57, 57)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tNombre)
                                    .addComponent(tDireccion)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(bNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void CrearPersona(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPersona
        String nombre = tNombre.getText();
        String direccion = tDireccion.getText();
        int edad = 0;
        int telefono = 0;
        try {
            edad = Integer.parseInt( tEdad.getText() );
        } catch (java.lang.NumberFormatException e) {
            dVacio.setVisible(true);
            tEdad.requestFocus();
        }
        try {
            telefono = Integer.parseInt( tTelefono.getText() );
        } catch (java.lang.NumberFormatException e) {
            dVacio.setVisible(true);
            tTelefono.requestFocus();
        }
        if("".equals(tNombre.getText())){
            dVacio.setVisible(true);
            tNombre.requestFocus();
        }else{
            if("".equals(tDireccion.getText())){
                dVacio.setVisible(true);
                tDireccion.requestFocus();
            }else{
                if("".equals(tEdad.getText())){
                    tEdad.requestFocus();
                }else{
                    if("".equals(tTelefono.getText())){
                        tTelefono.requestFocus(); 
                    }else{
                        TPersona persona = new TPersona(nombre,direccion,edad,telefono);
        
                        // Añade al arrayList el Objeto
                        agendaContactos.add(persona);
                        // Añade el nombre atributo al choice
                        cContacto.add(persona.getNombre());

                        // Limpiado tras creacion
                        tNombre.setText(null);
                        tDireccion.setText(null);
                        tEdad.setText(null);
                        tTelefono.setText(null);
                        tNombre.requestFocus();
                    }
                }
            }              
        }
    }//GEN-LAST:event_CrearPersona

    private void MostrarColeccion(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MostrarColeccion
        TPersona contacto = agendaContactos.get( cContacto.getSelectedIndex() );
        
        tNombre.setText( contacto.getNombre() );
        tNombre.requestFocus();
        tDireccion.setText( contacto.getDireccion() );
        tEdad.setText("" + contacto.getEdad() );
        tTelefono.setText("" + contacto.getTelefono() );
    }//GEN-LAST:event_MostrarColeccion

    private void BorrarContacto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarContacto
        System.out.println(cContacto.getItemCount());
        if (cContacto.getItemCount() > 0) {
            dBorrar.setVisible(true);
        }else{
            dBorrarVacio.setVisible(true);
        }
    }//GEN-LAST:event_BorrarContacto

    private void tTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTelefonoActionPerformed
        
        String nombre = tNombre.getText();
        String direccion = tDireccion.getText();
        int edad = 0;
        int telefono = 0;
        try {
            edad = Integer.parseInt( tEdad.getText() );
        } catch (java.lang.NumberFormatException e) {
            dVacio.setVisible(true);
            tEdad.requestFocus();
        }
        try {
            telefono = Integer.parseInt( tTelefono.getText() );
        } catch (java.lang.NumberFormatException e) {
            dVacio.setVisible(true);
            tTelefono.requestFocus();
        }
        if("".equals(tNombre.getText())){
            dVacio.setVisible(true);
            tNombre.requestFocus();
        }else{
            if("".equals(tDireccion.getText())){
                dVacio.setVisible(true);
                tDireccion.requestFocus();
            }else{
                if("".equals(tEdad.getText())){
                    tEdad.requestFocus();
                }else{
                    if("".equals(tTelefono.getText())){
                        tTelefono.requestFocus(); 
                    }else{
                        TPersona persona = new TPersona(nombre,direccion,edad,telefono);
        
                        // Añade al arrayList el Objeto
                        agendaContactos.add(persona);
                        // Añade el nombre atributo al choice
                        cContacto.add(persona.getNombre());

                        // Limpiado tras creacion
                        tNombre.setText(null);
                        tDireccion.setText(null);
                        tEdad.setText(null);
                        tTelefono.setText(null);
                        tNombre.requestFocus();
                    }
                }
            }              
        }
        
        
    }//GEN-LAST:event_tTelefonoActionPerformed

    private void tDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDireccionActionPerformed
        tEdad.requestFocus();
    }//GEN-LAST:event_tDireccionActionPerformed

    private void tEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEdadActionPerformed
        tTelefono.requestFocus();
    }//GEN-LAST:event_tEdadActionPerformed

    private void CerrarDialogoClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarDialogoClick
        dError.setVisible(false);
    }//GEN-LAST:event_CerrarDialogoClick

    private void ControlEdad(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ControlEdad
        try{
            int edad = Integer.parseInt( tEdad.getText() );
        }catch(NumberFormatException e){
            switch(tEdad.getText()){
                case "":
                    
                    break;
                default:
                    dError.setVisible(true);
            }
        }
    }//GEN-LAST:event_ControlEdad

    private void CerrarDialogoBoton(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CerrarDialogoBoton
        if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_ENTER) {
            dError.setVisible(false);
        }
    }//GEN-LAST:event_CerrarDialogoBoton

    private void ControlTelefono(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ControlTelefono
        try{
            int telefono = Integer.parseInt( tTelefono.getText() );
        }catch(NumberFormatException e){
            switch(tTelefono.getText()){
                case "":
                    
                    break;
                default:
                    dError.setVisible(true);
            }
        }
    }//GEN-LAST:event_ControlTelefono

    private void bAceptarBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarBorrarActionPerformed
       agendaContactos.remove( cContacto.getSelectedIndex() );
       cContacto.remove( cContacto.getSelectedIndex() );        
       
        //Limpiado tras borrado
        tNombre.setText(null);
        tDireccion.setText(null);
        tEdad.setText(null);
        tTelefono.setText(null);
        tNombre.requestFocus();
        dBorrar.setVisible(false);        
    }//GEN-LAST:event_bAceptarBorrarActionPerformed

    private void bCancelarBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarBorrarActionPerformed
        dBorrar.setVisible(false);
    }//GEN-LAST:event_bCancelarBorrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dBorrarVacio.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bBotonCerrarVacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBotonCerrarVacioActionPerformed
        dVacio.setVisible(false);
    }//GEN-LAST:event_bBotonCerrarVacioActionPerformed

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        tDireccion.requestFocus();
    }//GEN-LAST:event_tNombreActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptarBorrar;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bBotonCerrarVacio;
    private javax.swing.JButton bCancelarBorrar;
    private javax.swing.JButton bNuevo;
    private java.awt.Choice cContacto;
    private javax.swing.JDialog dBorrar;
    private javax.swing.JDialog dBorrarVacio;
    private javax.swing.JDialog dError;
    private javax.swing.JDialog dVacio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tDireccion;
    private javax.swing.JTextField tEdad;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables
}
