

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Victor
 */
public class ContadorPalabras extends javax.swing.JFrame {

    /**
     * Creates new form ContadorPalabras
     */
    public ContadorPalabras() {
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cSeparador = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        bAnalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAnalizar = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        taResultado = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        tPalabras = new javax.swing.JTextField();
        bNueva = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contador Palabras");
        setMinimumSize(new java.awt.Dimension(770, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("FRASE A ANALIZAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 690, 10));

        cSeparador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Punto", "Punto y Coma", "Coma", "Espacio en blanco" }));
        cSeparador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSeparadorActionPerformed(evt);
            }
        });
        getContentPane().add(cSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 120, -1));

        jLabel2.setText("Separador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        bAnalizar.setText("Analizar");
        bAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contadorPalabras(evt);
            }
        });
        getContentPane().add(bAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        taAnalizar.setColumns(20);
        taAnalizar.setRows(5);
        jScrollPane1.setViewportView(taAnalizar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 390, 120));

        jLabel3.setText("RESULTADO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 680, 10));

        taResultado.setEditable(false);
        taResultado.setColumns(20);
        taResultado.setRows(5);
        jScrollPane2.setViewportView(taResultado);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 390, 140));

        jLabel4.setText("Nº de palabras");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        tPalabras.setEditable(false);
        getContentPane().add(tPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 140, -1));

        bNueva.setText("Nueva");
        bNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevaActionPerformed(evt);
            }
        });
        getContentPane().add(bNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 90, -1));

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir(evt);
            }
        });
        getContentPane().add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cSeparadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSeparadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSeparadorActionPerformed

    private void contadorPalabras(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contadorPalabras
        String texto = taAnalizar.getText();
        int numPalabras = 0;
        System.out.println(texto);
        if ((String) cSeparador.getSelectedItem() == "Punto") {
            String[] resultado = texto.split("\\.");
            
            for (int i = 0; i < resultado.length; i++) {
                
                if (!resultado[i].isEmpty()) {
                    taResultado.append(""+resultado[i]+"\n");
                    numPalabras++;
                }else{
                    System.out.println("VALOR VACIO");
                }                
            }
            
            tPalabras.setText(""+numPalabras);
        } else if((String) cSeparador.getSelectedItem() == "Punto y Coma"){
            String[] resultado = texto.split(";");
            
            for (int i = 0; i < resultado.length; i++) {
                if (!resultado[i].isEmpty()) {
                    taResultado.append(""+resultado[i]+"\n");
                    numPalabras++;
                }else{
                    System.out.println("VALOR VACIO");
                }   
            }
            
            tPalabras.setText(""+numPalabras);
        }else if((String) cSeparador.getSelectedItem() == "Coma"){
            String[] resultado = texto.split(",");
            
            for (int i = 0; i < resultado.length; i++) {
                if (!resultado[i].isEmpty()) {
                    taResultado.append(""+resultado[i]+"\n");
                    numPalabras++;
                }else{
                    System.out.println("VALOR VACIO");
                }   
            }
            
            tPalabras.setText(""+numPalabras);
        }else if((String) cSeparador.getSelectedItem() == "Espacio en blanco"){
            String[] resultado = texto.split(" ");
            
            for (int i = 0; i < resultado.length; i++) {
                if (!resultado[i].isEmpty()) {
                    taResultado.append(""+resultado[i]+"\n");
                    numPalabras++;
                }else{
                    System.out.println("VALOR VACIO");
                }   
            }
            
            tPalabras.setText(""+numPalabras);
        }else{
            System.out.println("FALLO OBTENER SEPARADOR");
        }
    }//GEN-LAST:event_contadorPalabras

    private void bNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevaActionPerformed
        taAnalizar.setText(null);
        taResultado.setText(null);
        tPalabras.setText(null);
    }//GEN-LAST:event_bNuevaActionPerformed

    private void salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir
        System.exit(0);
    }//GEN-LAST:event_salir

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContadorPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContadorPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContadorPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContadorPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContadorPalabras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnalizar;
    private javax.swing.JButton bNueva;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> cSeparador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField tPalabras;
    private javax.swing.JTextArea taAnalizar;
    private javax.swing.JTextArea taResultado;
    // End of variables declaration//GEN-END:variables
}
